project_name                = "project-name"
project_owner               = "my-name"
ami_key_pair_name           = "my-keypair-name"
terraform_state_bucket_name = "project-terraform-state-bucket-name"
dynamodb_table_name         = "project-terraform-state-lock-table"